services:
  webapp:
    build:
      context: ./src
      dockerfile: Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - products-network
    container_name: sdi_api_dev
  
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password_123#
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - products-network
    container_name: sdi_db_dev

networks:
  products-network:

volumes:
  postgres_data: